version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  php:
    build: ./php
    ports: ['9000:9001']
    links:
      - mysql
    volumes:
      - ../symfony/:/var/www/symfony:cached
  nginx:
    build: ./nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ../logs/nginx:/var/log/nginx:cached
      - ../symfony/:/var/www/symfony:cached