api_login_check:
  path: /api/login_check

app_controllers:
  resource: '../src/Controller/'
  type: annotation

admin_controllers:
  resource: '../src/Bundle/AdminBundle/Controller/'
  type: annotation

news_controllers:
  resource: '../src/Bundle/NewsBundle/Controller/'
  type: annotation

user_controllers:
  resource: '../src/Bundle/UserBundle/Controller/'
  type: annotation